baseURL = "http://blog.aborilov.ru"
title = "IT Notes"
copyright = ""

theme = "minimo"

disqusShortname = "blog-aborilov-ru"
googleAnalytics = "UA-7387908-2"
Paginate = 5

preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Language Configuration
defaultContentLanguage = "en"

[params.info]
description = "Aborilov Pavel's thoughts"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Aborilov Pavel"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.opengraph.twitter]
page = "" # Twitter page username

[params.social]
email = "pavel@aborilov.ru"
facebook = "pavel.aborilov"
github = "aborilov"
twitter = "aborilov"
linkedin = "pavel-aborilov-19772bb0"

[params.social.config]
platforms = ["github","facebook","twitter","email","linkedin"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Main"
weight = -10
identifier = "main"
url = "http://blog.aborilov.ru"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
